### ISSUE TITLE
Add batch option to install plugins

### ISSUE THREAD

**Issue by antoniocascais** [bosh-elastic-stack/elasticsearch-boshrelease#4]
Hi.

I am trying to install the [repository-gcs pluging](https://www.elastic.co/guide/en/elasticsearch/plugins/6.4/repository-gcs.html), but I got an error when executing the pre-start script:
```
Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
```

I had a look and the problem is that we manually need to give input to promt in order to install the plugin.
This is the command that is executed in the pre-start script: `elasticsearch-plugin install "https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-gcs/repository-gcs-6.4.2.zip"`

I googled and there's a `--batch` option that automatically scripts promt: https://discuss.elastic.co/t/installing-plugin-through-shell-script-without-prompt/84456

Then I manually tried to execute the command `elasticsearch-plugin install "https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-gcs/repository-gcs-6.4.2.zip" --batch` and it works without prompt.

From what I've seen here, just adding the `--batch` option to the pre-start template solves this problem, but I'm not sure if you agree with the approach or if you want to make it opt-in (and, if so, how to do it).

Can you help and fix the issue? Or advise on how to proceed? I can also help with a PR if you prefer...

Thanks!

**Comment by making** [comment]
Does the installation from local path resolve that?

It looks like an official plugin.
I'm positive to bundle official plugins in this bosh-release.

https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/blob/master/packages/elasticsearch-plugins/spec

**Comment by antoniocascais** [comment]
Yes, it is an official plugin.

I tried from the local path and I get the same problem:
```-> Installed analysis-kuromoji
installing repository-gcs-6.4.2.zip
-> Downloading file:///var/vcap/packages/elasticsearch-plugins/repository-gcs-6.4.2.zip
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission setFactory
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]
```
It prompts the message and awaits for the input...

**Comment by making** [comment]
Thanks for the investigation.
I'm going to add a property that exposes command line parameters.

**Comment by antoniocascais** [comment]
Cool, thank you!

Let me know if I can help somehow :)

**Comment by making** [comment]
@antoniocascais Released [0.8.0](https://github.com/bosh-elastic-stack/elasticsearch-boshrelease/releases/tag/0.8.0) with `elasticsearch.plugin_install_opts` property.

I've confirmed the following ops-file worked:

```yaml
- type: replace
  path: /instance_groups/name=elasticsearch-master/jobs/name=elasticsearch/properties/elasticsearch/plugin_install_opts?
  value: 
  - --batch
- type: replace
  path: /instance_groups/name=elasticsearch-master/jobs/name=elasticsearch/properties/elasticsearch/plugins?
  value:
  - repository-gcs: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-gcs/repository-gcs-6.5.0.zip
  # - repository-gcs: repository-gcs # <- this also works
```
